import { user, banner } from "../assets";
import { news1 } from "../assets";
import {
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
  product10,
  product11,
  product12,
} from "../assets";

export const product = [
  {
    id: 101,
    image: product1,
    banner: banner,
    title: "Biệt đội Marvel",
    gener: ["Hành động", "Viễn tưởng", "Kịch tính"],
    year: 2019,
    time: "124 phút",
    rate: 4.2,
    actor: ["Brie Larson", "Samurel L.Jackson", "Ben Mendelsohn", "Jude Law"],
    director: "Anna Boden",
    nation: "USA",
    content:
      "Captain Marvel là một trong những siêu anh hùng mạnh nhất. Cô sở hữu một siêu năng lượng đặc biệt và những kỹ năng, kinh nghiệm chiến đấu khi còn trong quân đội, giúp cô trở thành thủ lĩnh của nhiều tổ chức, bao gồm cả đội Avengers.",
  },
  {
    id: 102,
    image: product2,
    banner: banner,
    title: "Avengers: Hồi kết",
    gener: ["Trinh thám", "Hành động", "Kịch tính"],
    year: 2019,
    time: "181 phút",
    rate: 7.6,
    actor: [
      "Robert Downey Jr",
      "Scarlett Johansson",
      "Chris Evans",
      "Chris Hemsworth",
      "Mark Ruffalo",
      "Jeremy Renner",
      "Brie Larson",
      "Paul Rudd",
    ],
    director: "Anthony Russo",
    nation: "Mỹ",
    content:
      "Phim khởi đầu sau sự kiện Infinity War năm 2018, Clint Barton (Hawkeye) cùng vợ con đi dã ngoại trong thời gian bị quản thúc. Ngay khi anh rời mắt khỏi gia đình mình một lát, họ tan biến thành tro bụi do là nạn nhân của sự kiện Búng tay.[a] Ba tuần sau, Carol Danvers (Captain Marvel) tìm thấy Tony Stark (Iron Man) đang bị thương và Nebula trôi dạt ngoài không gian trên con tàu vũ trụ Benatar sắp hết oxy, cô đưa họ về Trái Đất gặp lại những anh hùng còn sống sót khác, bao gồm Natasha Romanoff (Black Widow), Bruce Banner (Hulk), Steve Rogers (Captain America), Thor, Pepper Potts và James Rhodes (War Machine) và Rocket. Cú búng tay đã làm bay màu hầu hết các thành viên mới của Đội Avengers, chỉ còn lại những thành viên chủ chốt nêu trên. Họ kế hoạch lấy lại những Viên đá Vô cực từ Thanos với ý định sử dụng chúng để đảo ngược sự kiện Búng tay. Dựa vào sóng gamma, họ tìm thấy Thanos tại một hành tinh xa xôi nơi mà hắn lại sử dụng các viên đá vào hai tuần trước. Tony Stark ở lại Trái Đất dưỡng thương, cả nhóm lên kế hoạch tiến công và dễ dàng bắt được Thanos nay đã suy yếu, nhưng hắn đã phá hủy các viên đá để không ai sử dụng chúng được nữa. Trong cơn tức giận, Thor chém đầu Thanos, hành động đã trở nên vô nghĩa vì được thực hiện quá muộn. Năm năm sau, Trái Đất vẫn hoang tàn. Phần lớn anh hùng đã mỗi người một ngả, trong đó Danvers bay vào vũ trụ để giải quyết các hậu quả Thanos gây ra, còn Barton lấy biệt danh mới là Ronin và truy lùng xã hội đen trên khắp thế giới sau chuyện xảy ra với vợ con anh. Scott Lang (Ant-Man) cũng nằm trong danh sách những người mất tích, nhưng thực tế anh đang bị kẹt trong lượng tử giới. Sau khi tình cờ được giải thoát khỏi Lượng tử Giới nhờ một con chuột vô thức bước lên các nút điều khiển, Scott tìm hiểu nhanh chóng sự kiện búng tay, rồi đến trụ sở Avengers gặp Natasha và Steve. Từ trải nghiệm của bản thân, Scott cho biết năm năm vừa qua đối với anh chỉ là năm giờ bị mắc kẹt và du hành thời gian là có thể xảy ra. Cả ba tìm đến Tony, giờ đã kết hôn với Potts và có cô con gái nhỏ tên Morgan. Họ nêu giả thuyết quay lại quá khứ để thu thập các Viên đá Vô cực trước khi Thanos lấy được chúng. Stark từ chối vì lo sợ rủi ro xảy ra sẽ giết cả đội (vốn là gia đình mới trong tâm trí anh), cũng như sợ các rủi ro ảnh hưởng đến vợ con của mình. Vì vậy cả ba đành gặp Bruce, nay đã hợp nhất ý thức của mình với ngoại hình của Hulk và không còn phải trốn tránh xã hội. Hiểu biết về Lượng Tử Giới nằm ngoài chuyên môn khiến Bruce tạo ra cỗ máy có tác dụng ngược là đưa thời gian qua Scott. Cả nhóm trở nên bế tắc. Được Potts động viên và nhớ lại bức ảnh chụp chung với Peter Parker cầm ngược bằng, Stark chế tạo thành công thiết bị để giải trừ nghịch lý nói trên, đồng thời trao lại chiếc khiên được sửa sang cho Rogers. Bruce bác bỏ đề xuất về quá khứ giết em bé Thanos của Rhodes, giải thích rằng việc thay đổi quá khứ sẽ không thay đổi hiện tại mà chỉ vô ích, vì chẻ nhánh những dòng thời gian song song. Bruce và Rocket đến Tønsberg, Na Uy, còn được gọi là New Asgard đang có những người Asgard còn sống sót định cư, để tìm Thor, giờ là một gã nghiện bia thừa cân và ham chơi điện tử với Korg và Miek. Tại Tokyo, Romanoff khuyên bảo Barton trở về Mỹ sau khi chứng kiến anh tàn sát một tổ chức Yakuza. Các thành viên Biệt đội Avengers tập hợp và chia nhóm để quay lại quá khứ và thu thập đá Vô cực.[b] Tất cả sự kiện sau diễn ra cùng lúc và chỉ trong vòng năm giây ở dòng thời gian chính: Tại New York năm 2012, Bruce, Steve, Scott và Stark xuất hiện ngay trong trận chiến thành phố này[c] rồi chia nhau đi lấy các viên đá Thời gian (Time Stone), Không gian (Space Stone) và Trí tuệ (Mind Stone). Tại Thánh đường Sanctum Sanctorum, Thượng cổ Tôn Giả (Ancient One) đồng ý cho Bruce mượn Viên đá Thời gian sau khi nghe chuyện Stephen Strange (Doctor Strange) đã tự giao nó cho Thanos. Rồi Bruce quay về hiện tại. Scott và Tony thất bại trong việc lấy khối Tesseract, vô tình tạo cơ hội để Loki lấy được và trốn thoát cùng nó. Cùng lúc ấy, Steve dễ dàng lấy được cây quyền trượng từ nhóm gián điệp của HYDRA trong S.H.I.E.L.D. chỉ bằng lời thì thầm Hail HYDRA. Rồi anh bất ngờ gặp và phải đấu với chính mình trong quá khứ, do Loki đã trốn thoát và Steve lúc đó hiểu lầm rằng phiên bản Steve tương lai là Loki giả mạo. Steve hiện tại giành chiến thắng bằng mẹo tiết lộ Bucky Baes còn sống, rồi đánh ngất đối thủ đang ngạc nhiên nhờ sức mạnh của cây trượng. Sau khi giao cây trượng cho Scott về trước, Tony cùng Captain tiếp tục quay về quá khứ. Tại Trại Lehigh[d] năm 1970, hai người cải trang để lấy phiên bản cũ của khối Tesseract và thêm hạt Pym để quay về hiện tại. Ngay khi lấy được khối Tesseract, Stark vô tình gặp cha mình, Howard Stark, bấy giờ đang đợi đứa con chào đời. Cuộc gặp gỡ này giúp Stark hiểu được tấm lòng của bố mình, và anh đã tận dụng cơ hội này để gián tiếp cảm ơn ông. Trong khi đó, sau khi đánh cắp được một số hạt Pym từ phòng thí nghiệm của Hank Pym, Steve phải nấp ở nơi tình cờ là văn phòng của Peggy Carter, và thấy cô ở bên kia cửa sổ. Sau một khoảnh khắc trầm tư, Steve lặng lẽ rời đi. Gặp nhau ở bên ngoài, Steve và Stark cùng nhau quay về hiện tại. Tại Asgard năm 2013, ngay trước cuộc chiến với Dark Elf, trong lúc Rocket lấy Viên đá Thực tại (Reality Stone) bằng cách sử dụng thiết bị trích xuất Aether trong người Jane Foster,[e] Thor tái ngộ người mẹ Frigga, và mượn cây búa Mjolnir. Sau một hồi trò chuyện, Thor và Rocket tạm biệt Frigga và quay về hiện tại. Tại Morag năm 2014, Nebula và Rhodes ngồi chờ Peter Quill (Star-Lord) dẫn đường và đánh anh ta bất tỉnh, sau đó lấy dụng cụ mở cửa của anh ta và đi vào trong thu thập được Quả Cầu.[f] Rhodes trở về hiện tại cùng Viên đá Sức mạnh (Power Stone), nhưng Nebula bị mất kiểm soát do xung đột ý thức với chính mình trong quá khứ (2014) và kẹt lại ở Morag. Thanos (phiên bản quá khứ năm 2014) bắt được Nebula hiện tại và xem dữ liệu trong bộ nhớ của cô, nhờ đó hắn biết được kế hoạch của Biệt đội Avengers nhằm đảo ngược thành công hắn đã đạt được ở tương lai. Hắn cử Nebula phiên bản năm 2014 đến hiện tại và trà trộn vào trong Biệt đội Avengers. Thanos ở thời điểm này dù không nắm giữ đá vô cực, nhưng thực lực rất mạnh và hung hãn (sẽ mô tả trong phần phụ). Barton và Romanoff được giao con tàu vũ trụ Benatar, đặt chân đến hành tinh Vormir năm 2014, gặp linh hồn Red Skull để thu thập Viên đá Linh hồn (Soul Stone) và biết rằng ai muốn sở hữu Viên đá thì phải mất đi một người mà mình yêu quý. Sau một hồi tranh chấp, Romanoff chủ động buông tay rơi xuống vực sâu, để lại một mình Barton đau lòng quay về hiện tại với Soul Stone. Sau khi trở về hiện tại cùng sáu Viên đá, những người còn lại mới hay tin Romanoff đã hi sinh nên đã dành thời gian mặc niệm cô ở bờ hồ. Sau khi bình tĩnh trở lại, họ lắp những viên đá vào một chiếc Găng tay Nano do Tony chế tạo. Bruce, người duy nhất vừa chịu được bức xạ gamma vừa có tinh thần đủ vững vàng, búng tay thành công để hồi sinh những người đã bị xóa sổ, mặc dù chiếc găng lẫn cánh tay phải của anh chịu tổn thương nặng từ các viên đá ngay khi đeo găng. Đúng lúc đó, Nebula quá khứ sử dụng cỗ máy thời gian để đưa Thanos và binh đoàn của hắn ở năm 2014 đến hiện tại. Trụ sở Avengers nhanh chóng bị phá hủy, và trong đống đổ nát, Barton tìm được chiếc Găng tay cùng sáu Viên đá. Nebula hiện tại thuyết phục Gamora quá khứ chống lại Thanos, rồi đành tiêu diệt bản thể quá khứ của mình vì cô ta không nghe lời. Thanos, giờ đây đã đổi ý, quyết định sử dụng các Viên đá để hủy diệt cả vũ trụ và tạo ra một vũ trụ mới không chút tàn dư của cái cũ. Ba anh hùng đầu tiên thoát khỏi đống đổ nát là Steve, Tony và Thor hợp sức tấn công Thanos nhưng bị hắn áp đảo khá dễ dàng. Thor từ một á thần sấm sét trở nên vô dụng với thân hình béo ục ịch hiện tại, còn Tony lại không thể nhanh và mạnh bằng Thanos nên nhanh chóng bại trận. Việc Steve sử dụng búa Mjolnir giải cứu Thor chỉ giúp anh trụ được lâu hơn một lúc trước khi bị hắn phá huỷ chiếc khiên. Do chưa từng có kinh nghiệm chiến đấu với một eteal hiếu chiến như Thanos, lại chưa từng tập luyện sử dụng Mjolnir, nên Steve bị Thanos áp đảo hoàn toàn. Trong lúc tình hình đang nguy cấp, Strange, Wong cùng đội quân pháp sư xuất hiện, họ triệu tập các siêu anh hùng và các đội quân của Wakanda, Asgard, Ravagers, gồm tất cả những người sống sót hoặc đã được hồi sinh, cộng thêm Scott hóa khổng lồ và những người được anh giải cứu bao gồm Banner, Rhodes và Rocket. Danvers từ vũ trụ quay về đã phá hủy con tàu của Thanos, tiếp viện cho Avengers chống lại Thanos và binh đoàn của hắn. Sau một trận chiến dai dẳng và kịch liệt, với việc phần lớn siêu anh hùng đang bận chiến đấu không thể chống đỡ nổi đoàn quân xâm lăng. Thanos cướp được chiếc găng, nhưng trong nỗ lực giằng co tưởng như vô ích, Tony đã lén dịch chuyển các viên đá vào tay bộ giáp Mark LXXXV của mình. Anh búng tay xóa sổ Thanos cùng toàn bộ tay sai của hắn, nhưng sức mạnh quá lớn của các viên đá về sau cũng cướp đi mạng sống của anh. Sau đám tang của Tony Stark, Thor nhường ngai vàng của Asgard cho Valkyrie và gia nhập nhóm Vệ binh dải Ngân Hà (Guardians of the Galaxy). Valkyrie về sau trở thành thị trưởng thị trấn New Asgard. Quill bắt đầu đi tìm Gamora[g]. Steve đem trả các Viên đá và cây búa Mjolnir về đúng với vị trí của chúng trong quá khứ, rồi quyết định sống nốt quá khứ mà anh đã bỏ lỡ sau khi bị đóng băng vào năm 1945, bằng cách chui vào một dòng thời gian lỗi. Ở hiện tại, Steve, nay đã già và trở về tử quá khứ, trao chiếc khiên từ quá khứ của mình cho Sam Wilson. Kết thúc phim là cảnh hạnh phúc của Steve trong dòng thời gian nêu trêu, khi được khiêu vũ cùng với người vợ đã cưới là Peggy Carter rồi họ hôn nhau. Sau phần danh đề, đặc biệt là phân đoạn tri ân sáu thành viên đầu tiên của đội Avengers, là vài tiếng rèn kim loại vang lên trong lúc logo Marvel Studios xuất hiện, đây là âm thanh khi Stark đang rèn bộ áo giáp Mark I, như một sự tưởng niệm với anh.",
  },
  {
    id: 103,
    image: product3,
    banner: banner,
    title: "Oppenheimer",
    gener: ["Chiếu rạp", "Viễn tưởng", "Lịch sử", "Tâm lý"],
    year: 2023,
    time: "180 phút",
    rate: 9.0,
    actor: [
      "Cillian Murphy",
      "Robert Downey Jr",
      "Florence Pugh",
      "Emily Blunt",
      "Devon Bostick",
    ],
    director: "Christopher Nolan",
    nation: "USA",
    content:
      'Oppenheimer 2023 là một phiên bản chuyển thể từ cuốn sách American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer của Martin Sherwin và Kai Bird. Cuốn sách đoạt giải Pulitzer đang được chuyển thể thành một bộ phim được mô tả là "một bộ phim hành động kịch tính siêu nét IMAX đưa khán giả vào cuộc sống rùng rợn đối lập của người đàn ông huyền bí, người phải liều mình phá hủy thế giới để cứu nó".Oppenheimer là một nhà khoa học nổi tiếng nhất vì ông đã dẫn đầu Dự án Manhattan - đội ngũ phát triển bom nguyên tử cho Hoa Kỳ trong Thế chiến II. Sau đó, ông làm việc làm chủ tịch Ủy ban Năng lượng Nguyên tử Hoa Kỳ, nơi ông cố gắng làm chậm sự đua tranh vũ khí hạt nhân đang phát triển với Liên Xô.',
  },
  {
    id: 104,
    image: product4,
    banner: banner,
    title: "Hành tinh cát 2",
    gener: ["Hành dộng", "Chiếu rạp", "Khoa học", "Phiêu lưu", "Viễn tưởng"],
    year: 2023,
    time: "130 phút",
    rate: 7.4,
    actor: [
      "Timothée Chalamet",
      "Zendaya",
      "Rebecca Ferguson",
      "Josh Brolin",
      "Austin Butler",
      "Florence Pugh",
    ],
    director: "Denis Villeneuve",
    nation: "USA",
    content:
      "Hành Tinh Cát 2 - Dune: Part Two (2023)  công tước Paul Atreides gia nhập cùng chủng tộc người bản đại Fremen trên hành tinh Arrakis và bắt đầu cuộc hành trình nhằm rèn luyện tinh thần cũng như thể chất để trở thành Muad'dib - người đứng đầu tộc Fremen. Cùng với đó, anh phải cố gắng ngăn chặn tương lai khủng khiếp mà bản thân đã nhìn thấy nhờ Hương Dược: một cuộc Thánh chiến nhân danh anh, lan rộng khắp vũ trụ đã biết.",
  },
  {
    id: 105,
    image: product5,
    banner: banner,
    title: "John Wick 4",
    gener: ["Chiếu rạp", "Hành động", "Hình sự", "Kịch tính", "Tâm lý"],
    year: 2024,
    time: "169 phút",
    rate: 8.7,
    actor: [
      "Keanu Reeves",
      "Donnie Yen",
      "Ian McShane",
      "Bill Skarsgård",
      "Laurence Fishburne",
      "Hiroyuki Sanada",
      "Lance Reddick",
    ],
    director: "Chad Stahelski",
    nation: "USA",
    content:
      "John Wick: Chapter 4 là câu chuyện của John Wick (Keanu Reeves) đã khám phá ra con đường để đánh bại High Table. Nhưng trước khi có thể kiếm được tự do, Wick phải đối đầu với kẻ thù mới với những liên minh hùng mạnh trên toàn cầu và những lực lượng biến những người bạn cũ thành kẻ thù.",
  },
  {
    id: 106,
    image: product6,
    banner: banner,
    title: "Quý cô mạng nhện",
    gener: ["Hành động", "Viễn tưởng", "Khoa học"],
    year: 2024,
    time: "116 phút",
    rate: 4.3,
    actor: [
      "Dakota Johnson",
      "Sydney Sweeney",
      "Isabela Merced",
      "Celeste O'Connor",
      "Celeste O'Connor",
      "Kerry Bishé",
    ],
    director: "S.J. Clarkson",
    nation: "USA",
    content:
      "Bộ phim kể về nguồn gốc của một đồng minh Người Nhện, một nhân vật trong truyện tranh Marvel có sức mạnh liên kết đa vũ trụ - Cassandra Webb (Dakota Johnson) hay còn được biết đến là Madame Web. Sở hữu khả năng và giác quan nhạy bén của loài nhện, Cassandra có khả năng thấu thị, thần giao cách cảm và nhìn trước tương lai. Chính từ đây mà số phận của cô ấy trở nên gắn bó một cách bí ẩn với ba cô gái khác là Julia Carpenter (Sydney Sweeney), Anya Corazon (Isabela Merced) và Mattie Franklin (Celeste O'Connor) - những người được dự đoán là thế hệ tương lai của Người Nhện.",
  },
  {
    id: 107,
    image: product7,
    banner: banner,
    title: "Trận Chiến Tàn Khốc",
    gener: ["Chiến tranh", "Hành động"],
    year: 2024,
    time: "113 phút",
    rate: 8.4,
    actor: [
      "Liam Hemsworth",
      "Russell Crowe",
      "Luke Hemsworth",
      "Ricky Whittle",
      "Milo Ventimiglia",
    ],
    director: "William Eubank",
    nation: "Australia",
    content:
      "Khi một nhiệm vụ đặc biệt của Lực lượng Delta gặp trục trặc nghiêm trọng, phi công lái máy bay không người lái Reaper của Lực lượng Không quân có 48 giờ để khắc phục những gì đã biến thành một chiến dịch giải cứu hoang dã. Không có vũ khí và không có phương tiện liên lạc nào ngoài chiếc máy bay không người lái phía trên, nhiệm vụ trên mặt đất",
  },
  {
    id: 108,
    image: product8,
    title: "Einstein Và Trái Bom",
    gener: ["Chính kịch", "Tài liệu", "Lịch sử"],
    year: 2024,
    time: "76 phút",
    rate: 7.9,
    actor: [
      "Aidan McArdle",
      "Andrew Havill",
      "Rachel Barry",
      "Helena Westerman",
      "Leo Ashizawa",
    ],
    director: "Anthony Philipson",
    nation: "United Kingdom",
    content:
      "Chuyện gì xảy ra sau khi Einstein trốn khỏi Đức Quốc xã? Qua phim tư liệu và lời chia sẻ của chính ông, bộ phim tài liệu chính kịch này đào sâu tâm trí của thiên tài bị dằn vặt.",
  },
  {
    id: 109,
    image: product9,
    title: "Quán Ăn Quỷ Đói",
    gener: ["Chính kịch", "Kịch tính", "Kinh dị"],
    year: 2023,
    time: "116 phút",
    rate: 5.5,
    actor: [
      "Chen Keat Yoke",
      "Eric Chen",
      "Sam Chong",
      "Fabian Loo",
      "Julie Chew",
    ],
    director: "Cho We Jun",
    nation: "Malaysia",
    content:
      "Mắc kẹt ở quê nhà trong thời gian phong tỏa vì đại dịch, Bonnie đến ở nhờ tại quán cà phê cũ của gia đình và phát hiện hàng loạt bất ngờ rùng rợn.",
  },
  {
    id: 110,
    image: product10,
    title: "Thiếu Niên Và Chim Diệc",
    gener: ["Chính kịch", "Hoạt hình", "Phiêu lưu", "Viễn tưởng"],
    year: 2023,
    time: "124 phút",
    rate: 8.4,
    actor: [
      "Soma Santoki",
      "Masaki Suda",
      "Ko Shibasaki",
      "Aimyon",
      "Yoshino Kimura",
      "Takuya Kimura",
      "Keiko Takeshita",
      "Jun Fubuki",
      "Sawako Agawa",
      "Karen Takizawa",
    ],
    director: "Hayao Miyazaki",
    nation: "Japan",
    content:
      "Thiếu Niên Và Chim Diệc The Boy and the Heron (2023) đến từ Studio Ghibli và đạo diễn Miyazaki Hayao, bộ phim là câu chuyện về hành trình kỳ diệu của cậu thiếu niên Mahito trong một thế giới hoàn toàn mới lạ. Trải qua nỗi đau mất mẹ cùng mối quan hệ chẳng mấy vui vẻ với gia đình cũng như bạn học, Mahito dần cô lập bản thân… cho đến khi cậu gặp một chú chim diệc biết nói kỳ lạ. Mahito cùng chim diệc bước vào một tòa tháp bí ẩn, nơi một thế giới thần kỳ mở ra, đưa cậu gặp gỡ những người mình yêu thương… trong một nhân dạng hoàn toàn khác.",
  },
  {
    id: 111,
    image: product11,
    title: "Godzilla Đại Chiến Kong",
    gener: ["Hành động", "Kịch tính", "Phiêu lưu", "Viễn tưởng"],
    year: 2021,
    time: "114 phút",
    rate: 9.1,
    actor: [
      "Alexander Skarsgård",
      "Millie Bobby Brown",
      "Rebecca Hall",
      "Brian Tyree Henry",
      "Shun Oguri",
      "Eiza González",
      "Julian Dennison",
      "Lance Reddick",
      "Kyle Chandler",
      "Demián Bichir",
    ],
    director: "Adam Wingard",
    nation: "USA",
    content:
      "Godzilla Đại Chiến Kong - Godzilla vs. Kong (2021) khi hai kẻ thù truyền kiếp gặp nhau trong một trận chiến ngoạn mục, số phận của cả thế giới vẫn còn bị bỏ ngỏ… Bị đưa khỏi Đảo Đầu Lâu, Kong cùng Jia, một cô bé mồ côi có mối liên kết mạnh mẽ với mình và đội bảo vệ đặc biệt hướng về mái nhà mới. Bất ngờ, nhóm đụng độ phải Godzilla hùng mạnh, tạo ra một làn sóng hủy diệt trên toàn cầu. Thực chất, cuộc chiến giữa hai kẻ khổng lồ dưới sự thao túng của các thế lực vô hình mới chỉ là điểm khởi đầu để khám phá những bí ẩn nằm sâu trong tâm Trái đất.",
  },
  {
    id: 112,
    image: product12,
    title: "Tình Chị Duyên Em",
    gener: ["Chiếu rạp", "Chính kịch", "Tâm lý", "Tình cảm"],
    year: 2023,
    time: "122 phút",
    rate: 9.8,
    actor: [
      "Thitiya Jirapornsilp",
      "Anthony Buisseret",
      "Supakson Chaimongkol",
      "Natee Ngamneawprom",
      "Karuna Looktumthong",
      "Kantapon Jindataweephol",
      "Pratya Patong",
    ],
    director: "Chantavit Dhanasevi",
    nation: "Thailand",
    content:
      "Tình Chị Duyên Em - You & Me & Me (2023) tình chị em tưởng chừng không thể rạn nứt cho đến khi chàng trai Mark chen vào giữa họ. Khi cặp song sinh phải đối mặt với “mối tình đầu không thể chia sẻ” như những thứ khác, cuộc xung đột nội tâm này sẽ dẫn họ bước sang giai đoạn mới của cuộc đời như thế nào?",
  },
  {
    id: 113,
    image: product1,
    title: "Đại úy Marvel",
    gener: ["Hành động", "Viễn tưởng", "Kịch tính"],
    year: 2019,
    time: "124 phút",
    rate: 4.2,
    actor: ["Brie Larson", "Samurel L.Jackson", "Ben Mendelsohn", "Jude Law"],
    director: "Anna Boden",
    nation: "USA",
    content:
      "Captain Marvel là một trong những siêu anh hùng mạnh nhất. Cô sở hữu một siêu năng lượng đặc biệt và những kỹ năng, kinh nghiệm chiến đấu khi còn trong quân đội, giúp cô trở thành thủ lĩnh của nhiều tổ chức, bao gồm cả đội Avengers.",
  },
  {
    id: 114,
    image: product2,
    title: "Avengers: Hồi kết",
    gener: ["Trinh thám", "Hành động", "Kịch tính"],
    year: 2019,
    time: "181 phút",
    rate: 7.6,
    actor: [
      "Robert Downey Jr",
      "Scarlett Johansson",
      "Chris Evans",
      "Chris Hemsworth",
      "Mark Ruffalo",
      "Jeremy Renner",
      "Brie Larson",
      "Paul Rudd",
    ],
    director: "Anthony Russo",
    nation: "Mỹ",
    content:
      "Phim khởi đầu sau sự kiện Infinity War năm 2018, Clint Barton (Hawkeye) cùng vợ con đi dã ngoại trong thời gian bị quản thúc. Ngay khi anh rời mắt khỏi gia đình mình một lát, họ tan biến thành tro bụi do là nạn nhân của sự kiện Búng tay.[a] Ba tuần sau, Carol Danvers (Captain Marvel) tìm thấy Tony Stark (Iron Man) đang bị thương và Nebula trôi dạt ngoài không gian trên con tàu vũ trụ Benatar sắp hết oxy, cô đưa họ về Trái Đất gặp lại những anh hùng còn sống sót khác, bao gồm Natasha Romanoff (Black Widow), Bruce Banner (Hulk), Steve Rogers (Captain America), Thor, Pepper Potts và James Rhodes (War Machine) và Rocket. Cú búng tay đã làm bay màu hầu hết các thành viên mới của Đội Avengers, chỉ còn lại những thành viên chủ chốt nêu trên. Họ kế hoạch lấy lại những Viên đá Vô cực từ Thanos với ý định sử dụng chúng để đảo ngược sự kiện Búng tay. Dựa vào sóng gamma, họ tìm thấy Thanos tại một hành tinh xa xôi nơi mà hắn lại sử dụng các viên đá vào hai tuần trước. Tony Stark ở lại Trái Đất dưỡng thương, cả nhóm lên kế hoạch tiến công và dễ dàng bắt được Thanos nay đã suy yếu, nhưng hắn đã phá hủy các viên đá để không ai sử dụng chúng được nữa. Trong cơn tức giận, Thor chém đầu Thanos, hành động đã trở nên vô nghĩa vì được thực hiện quá muộn. Năm năm sau, Trái Đất vẫn hoang tàn. Phần lớn anh hùng đã mỗi người một ngả, trong đó Danvers bay vào vũ trụ để giải quyết các hậu quả Thanos gây ra, còn Barton lấy biệt danh mới là Ronin và truy lùng xã hội đen trên khắp thế giới sau chuyện xảy ra với vợ con anh. Scott Lang (Ant-Man) cũng nằm trong danh sách những người mất tích, nhưng thực tế anh đang bị kẹt trong lượng tử giới. Sau khi tình cờ được giải thoát khỏi Lượng tử Giới nhờ một con chuột vô thức bước lên các nút điều khiển, Scott tìm hiểu nhanh chóng sự kiện búng tay, rồi đến trụ sở Avengers gặp Natasha và Steve. Từ trải nghiệm của bản thân, Scott cho biết năm năm vừa qua đối với anh chỉ là năm giờ bị mắc kẹt và du hành thời gian là có thể xảy ra. Cả ba tìm đến Tony, giờ đã kết hôn với Potts và có cô con gái nhỏ tên Morgan. Họ nêu giả thuyết quay lại quá khứ để thu thập các Viên đá Vô cực trước khi Thanos lấy được chúng. Stark từ chối vì lo sợ rủi ro xảy ra sẽ giết cả đội (vốn là gia đình mới trong tâm trí anh), cũng như sợ các rủi ro ảnh hưởng đến vợ con của mình. Vì vậy cả ba đành gặp Bruce, nay đã hợp nhất ý thức của mình với ngoại hình của Hulk và không còn phải trốn tránh xã hội. Hiểu biết về Lượng Tử Giới nằm ngoài chuyên môn khiến Bruce tạo ra cỗ máy có tác dụng ngược là đưa thời gian qua Scott. Cả nhóm trở nên bế tắc. Được Potts động viên và nhớ lại bức ảnh chụp chung với Peter Parker cầm ngược bằng, Stark chế tạo thành công thiết bị để giải trừ nghịch lý nói trên, đồng thời trao lại chiếc khiên được sửa sang cho Rogers. Bruce bác bỏ đề xuất về quá khứ giết em bé Thanos của Rhodes, giải thích rằng việc thay đổi quá khứ sẽ không thay đổi hiện tại mà chỉ vô ích, vì chẻ nhánh những dòng thời gian song song. Bruce và Rocket đến Tønsberg, Na Uy, còn được gọi là New Asgard đang có những người Asgard còn sống sót định cư, để tìm Thor, giờ là một gã nghiện bia thừa cân và ham chơi điện tử với Korg và Miek. Tại Tokyo, Romanoff khuyên bảo Barton trở về Mỹ sau khi chứng kiến anh tàn sát một tổ chức Yakuza. Các thành viên Biệt đội Avengers tập hợp và chia nhóm để quay lại quá khứ và thu thập đá Vô cực.[b] Tất cả sự kiện sau diễn ra cùng lúc và chỉ trong vòng năm giây ở dòng thời gian chính: Tại New York năm 2012, Bruce, Steve, Scott và Stark xuất hiện ngay trong trận chiến thành phố này[c] rồi chia nhau đi lấy các viên đá Thời gian (Time Stone), Không gian (Space Stone) và Trí tuệ (Mind Stone). Tại Thánh đường Sanctum Sanctorum, Thượng cổ Tôn Giả (Ancient One) đồng ý cho Bruce mượn Viên đá Thời gian sau khi nghe chuyện Stephen Strange (Doctor Strange) đã tự giao nó cho Thanos. Rồi Bruce quay về hiện tại. Scott và Tony thất bại trong việc lấy khối Tesseract, vô tình tạo cơ hội để Loki lấy được và trốn thoát cùng nó. Cùng lúc ấy, Steve dễ dàng lấy được cây quyền trượng từ nhóm gián điệp của HYDRA trong S.H.I.E.L.D. chỉ bằng lời thì thầm Hail HYDRA. Rồi anh bất ngờ gặp và phải đấu với chính mình trong quá khứ, do Loki đã trốn thoát và Steve lúc đó hiểu lầm rằng phiên bản Steve tương lai là Loki giả mạo. Steve hiện tại giành chiến thắng bằng mẹo tiết lộ Bucky Baes còn sống, rồi đánh ngất đối thủ đang ngạc nhiên nhờ sức mạnh của cây trượng. Sau khi giao cây trượng cho Scott về trước, Tony cùng Captain tiếp tục quay về quá khứ. Tại Trại Lehigh[d] năm 1970, hai người cải trang để lấy phiên bản cũ của khối Tesseract và thêm hạt Pym để quay về hiện tại. Ngay khi lấy được khối Tesseract, Stark vô tình gặp cha mình, Howard Stark, bấy giờ đang đợi đứa con chào đời. Cuộc gặp gỡ này giúp Stark hiểu được tấm lòng của bố mình, và anh đã tận dụng cơ hội này để gián tiếp cảm ơn ông. Trong khi đó, sau khi đánh cắp được một số hạt Pym từ phòng thí nghiệm của Hank Pym, Steve phải nấp ở nơi tình cờ là văn phòng của Peggy Carter, và thấy cô ở bên kia cửa sổ. Sau một khoảnh khắc trầm tư, Steve lặng lẽ rời đi. Gặp nhau ở bên ngoài, Steve và Stark cùng nhau quay về hiện tại. Tại Asgard năm 2013, ngay trước cuộc chiến với Dark Elf, trong lúc Rocket lấy Viên đá Thực tại (Reality Stone) bằng cách sử dụng thiết bị trích xuất Aether trong người Jane Foster,[e] Thor tái ngộ người mẹ Frigga, và mượn cây búa Mjolnir. Sau một hồi trò chuyện, Thor và Rocket tạm biệt Frigga và quay về hiện tại. Tại Morag năm 2014, Nebula và Rhodes ngồi chờ Peter Quill (Star-Lord) dẫn đường và đánh anh ta bất tỉnh, sau đó lấy dụng cụ mở cửa của anh ta và đi vào trong thu thập được Quả Cầu.[f] Rhodes trở về hiện tại cùng Viên đá Sức mạnh (Power Stone), nhưng Nebula bị mất kiểm soát do xung đột ý thức với chính mình trong quá khứ (2014) và kẹt lại ở Morag. Thanos (phiên bản quá khứ năm 2014) bắt được Nebula hiện tại và xem dữ liệu trong bộ nhớ của cô, nhờ đó hắn biết được kế hoạch của Biệt đội Avengers nhằm đảo ngược thành công hắn đã đạt được ở tương lai. Hắn cử Nebula phiên bản năm 2014 đến hiện tại và trà trộn vào trong Biệt đội Avengers. Thanos ở thời điểm này dù không nắm giữ đá vô cực, nhưng thực lực rất mạnh và hung hãn (sẽ mô tả trong phần phụ). Barton và Romanoff được giao con tàu vũ trụ Benatar, đặt chân đến hành tinh Vormir năm 2014, gặp linh hồn Red Skull để thu thập Viên đá Linh hồn (Soul Stone) và biết rằng ai muốn sở hữu Viên đá thì phải mất đi một người mà mình yêu quý. Sau một hồi tranh chấp, Romanoff chủ động buông tay rơi xuống vực sâu, để lại một mình Barton đau lòng quay về hiện tại với Soul Stone. Sau khi trở về hiện tại cùng sáu Viên đá, những người còn lại mới hay tin Romanoff đã hi sinh nên đã dành thời gian mặc niệm cô ở bờ hồ. Sau khi bình tĩnh trở lại, họ lắp những viên đá vào một chiếc Găng tay Nano do Tony chế tạo. Bruce, người duy nhất vừa chịu được bức xạ gamma vừa có tinh thần đủ vững vàng, búng tay thành công để hồi sinh những người đã bị xóa sổ, mặc dù chiếc găng lẫn cánh tay phải của anh chịu tổn thương nặng từ các viên đá ngay khi đeo găng. Đúng lúc đó, Nebula quá khứ sử dụng cỗ máy thời gian để đưa Thanos và binh đoàn của hắn ở năm 2014 đến hiện tại. Trụ sở Avengers nhanh chóng bị phá hủy, và trong đống đổ nát, Barton tìm được chiếc Găng tay cùng sáu Viên đá. Nebula hiện tại thuyết phục Gamora quá khứ chống lại Thanos, rồi đành tiêu diệt bản thể quá khứ của mình vì cô ta không nghe lời. Thanos, giờ đây đã đổi ý, quyết định sử dụng các Viên đá để hủy diệt cả vũ trụ và tạo ra một vũ trụ mới không chút tàn dư của cái cũ. Ba anh hùng đầu tiên thoát khỏi đống đổ nát là Steve, Tony và Thor hợp sức tấn công Thanos nhưng bị hắn áp đảo khá dễ dàng. Thor từ một á thần sấm sét trở nên vô dụng với thân hình béo ục ịch hiện tại, còn Tony lại không thể nhanh và mạnh bằng Thanos nên nhanh chóng bại trận. Việc Steve sử dụng búa Mjolnir giải cứu Thor chỉ giúp anh trụ được lâu hơn một lúc trước khi bị hắn phá huỷ chiếc khiên. Do chưa từng có kinh nghiệm chiến đấu với một eteal hiếu chiến như Thanos, lại chưa từng tập luyện sử dụng Mjolnir, nên Steve bị Thanos áp đảo hoàn toàn. Trong lúc tình hình đang nguy cấp, Strange, Wong cùng đội quân pháp sư xuất hiện, họ triệu tập các siêu anh hùng và các đội quân của Wakanda, Asgard, Ravagers, gồm tất cả những người sống sót hoặc đã được hồi sinh, cộng thêm Scott hóa khổng lồ và những người được anh giải cứu bao gồm Banner, Rhodes và Rocket. Danvers từ vũ trụ quay về đã phá hủy con tàu của Thanos, tiếp viện cho Avengers chống lại Thanos và binh đoàn của hắn. Sau một trận chiến dai dẳng và kịch liệt, với việc phần lớn siêu anh hùng đang bận chiến đấu không thể chống đỡ nổi đoàn quân xâm lăng. Thanos cướp được chiếc găng, nhưng trong nỗ lực giằng co tưởng như vô ích, Tony đã lén dịch chuyển các viên đá vào tay bộ giáp Mark LXXXV của mình. Anh búng tay xóa sổ Thanos cùng toàn bộ tay sai của hắn, nhưng sức mạnh quá lớn của các viên đá về sau cũng cướp đi mạng sống của anh. Sau đám tang của Tony Stark, Thor nhường ngai vàng của Asgard cho Valkyrie và gia nhập nhóm Vệ binh dải Ngân Hà (Guardians of the Galaxy). Valkyrie về sau trở thành thị trưởng thị trấn New Asgard. Quill bắt đầu đi tìm Gamora[g]. Steve đem trả các Viên đá và cây búa Mjolnir về đúng với vị trí của chúng trong quá khứ, rồi quyết định sống nốt quá khứ mà anh đã bỏ lỡ sau khi bị đóng băng vào năm 1945, bằng cách chui vào một dòng thời gian lỗi. Ở hiện tại, Steve, nay đã già và trở về tử quá khứ, trao chiếc khiên từ quá khứ của mình cho Sam Wilson. Kết thúc phim là cảnh hạnh phúc của Steve trong dòng thời gian nêu trêu, khi được khiêu vũ cùng với người vợ đã cưới là Peggy Carter rồi họ hôn nhau. Sau phần danh đề, đặc biệt là phân đoạn tri ân sáu thành viên đầu tiên của đội Avengers, là vài tiếng rèn kim loại vang lên trong lúc logo Marvel Studios xuất hiện, đây là âm thanh khi Stark đang rèn bộ áo giáp Mark I, như một sự tưởng niệm với anh.",
  },
  {
    id: 115,
    image: product3,
    title: "Oppenheimer",
    gener: ["Chiếu rạp", "Viễn tưởng", "Lịch sử", "Tâm lý"],
    year: 2023,
    time: "180 phút",
    rate: 9.0,
    actor: [
      "Cillian Murphy",
      "Robert Downey Jr",
      "Florence Pugh",
      "Emily Blunt",
      "Devon Bostick",
    ],
    director: "Christopher Nolan",
    nation: "USA",
    content:
      'Oppenheimer 2023 là một phiên bản chuyển thể từ cuốn sách American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer của Martin Sherwin và Kai Bird. Cuốn sách đoạt giải Pulitzer đang được chuyển thể thành một bộ phim được mô tả là "một bộ phim hành động kịch tính siêu nét IMAX đưa khán giả vào cuộc sống rùng rợn đối lập của người đàn ông huyền bí, người phải liều mình phá hủy thế giới để cứu nó".Oppenheimer là một nhà khoa học nổi tiếng nhất vì ông đã dẫn đầu Dự án Manhattan - đội ngũ phát triển bom nguyên tử cho Hoa Kỳ trong Thế chiến II. Sau đó, ông làm việc làm chủ tịch Ủy ban Năng lượng Nguyên tử Hoa Kỳ, nơi ông cố gắng làm chậm sự đua tranh vũ khí hạt nhân đang phát triển với Liên Xô.',
  },
  {
    id: 116,
    image: product4,
    title: "Hành tinh cát 2",
    gener: ["Hành dộng", "Chiếu rạp", "Khoa học", "Phiêu lưu", "Viễn tưởng"],
    year: 2023,
    time: "130 phút",
    rate: 7.4,
    actor: [
      "Timothée Chalamet",
      "Zendaya",
      "Rebecca Ferguson",
      "Josh Brolin",
      "Austin Butler",
      "Florence Pugh",
    ],
    director: "Denis Villeneuve",
    nation: "USA",
    content:
      "Hành Tinh Cát 2 - Dune: Part Two (2023)  công tước Paul Atreides gia nhập cùng chủng tộc người bản đại Fremen trên hành tinh Arrakis và bắt đầu cuộc hành trình nhằm rèn luyện tinh thần cũng như thể chất để trở thành Muad'dib - người đứng đầu tộc Fremen. Cùng với đó, anh phải cố gắng ngăn chặn tương lai khủng khiếp mà bản thân đã nhìn thấy nhờ Hương Dược: một cuộc Thánh chiến nhân danh anh, lan rộng khắp vũ trụ đã biết.",
  },
  {
    id: 117,
    image: product5,
    title: "John Wick 4",
    gener: ["Chiếu rạp", "Hành động", "Hình sự", "Kịch tính", "Tâm lý"],
    year: 2024,
    time: "169 phút",
    rate: 8.7,
    actor: [
      "Keanu Reeves",
      "Donnie Yen",
      "Ian McShane",
      "Bill Skarsgård",
      "Laurence Fishburne",
      "Hiroyuki Sanada",
      "Lance Reddick",
    ],
    director: "Chad Stahelski",
    nation: "USA",
    content:
      "John Wick: Chapter 4 là câu chuyện của John Wick (Keanu Reeves) đã khám phá ra con đường để đánh bại High Table. Nhưng trước khi có thể kiếm được tự do, Wick phải đối đầu với kẻ thù mới với những liên minh hùng mạnh trên toàn cầu và những lực lượng biến những người bạn cũ thành kẻ thù.",
  },
  {
    id: 118,
    image: product6,
    title: "Quý cô mạng nhện",
    gener: ["Hành động", "Viễn tưởng", "Khoa học"],
    year: 2024,
    time: "116 phút",
    rate: 4.3,
    actor: [
      "Dakota Johnson",
      "Sydney Sweeney",
      "Isabela Merced",
      "Celeste O'Connor",
      "Celeste O'Connor",
      "Kerry Bishé",
    ],
    director: "S.J. Clarkson",
    nation: "USA",
    content:
      "Bộ phim kể về nguồn gốc của một đồng minh Người Nhện, một nhân vật trong truyện tranh Marvel có sức mạnh liên kết đa vũ trụ - Cassandra Webb (Dakota Johnson) hay còn được biết đến là Madame Web. Sở hữu khả năng và giác quan nhạy bén của loài nhện, Cassandra có khả năng thấu thị, thần giao cách cảm và nhìn trước tương lai. Chính từ đây mà số phận của cô ấy trở nên gắn bó một cách bí ẩn với ba cô gái khác là Julia Carpenter (Sydney Sweeney), Anya Corazon (Isabela Merced) và Mattie Franklin (Celeste O'Connor) - những người được dự đoán là thế hệ tương lai của Người Nhện.",
  },
  {
    id: 119,
    image: product7,
    title: "Trận Chiến Tàn Khốc",
    gener: ["Chiến tranh", "Hành động"],
    year: 2024,
    time: "113 phút",
    rate: 8.4,
    actor: [
      "Liam Hemsworth",
      "Russell Crowe",
      "Luke Hemsworth",
      "Ricky Whittle",
      "Milo Ventimiglia",
    ],
    director: "William Eubank",
    nation: "Australia",
    content:
      "Khi một nhiệm vụ đặc biệt của Lực lượng Delta gặp trục trặc nghiêm trọng, phi công lái máy bay không người lái Reaper của Lực lượng Không quân có 48 giờ để khắc phục những gì đã biến thành một chiến dịch giải cứu hoang dã. Không có vũ khí và không có phương tiện liên lạc nào ngoài chiếc máy bay không người lái phía trên, nhiệm vụ trên mặt đất",
  },
  {
    id: 120,
    image: product8,
    title: "Einstein Và Trái Bom",
    gener: ["Chính kịch", "Tài liệu", "Lịch sử"],
    year: 2024,
    time: "76 phút",
    rate: 7.9,
    actor: [
      "Aidan McArdle",
      "Andrew Havill",
      "Rachel Barry",
      "Helena Westerman",
      "Leo Ashizawa",
    ],
    director: "Anthony Philipson",
    nation: "United Kingdom",
    content:
      "Chuyện gì xảy ra sau khi Einstein trốn khỏi Đức Quốc xã? Qua phim tư liệu và lời chia sẻ của chính ông, bộ phim tài liệu chính kịch này đào sâu tâm trí của thiên tài bị dằn vặt.",
  },
  {
    id: 121,
    image: product9,
    title: "Quán Ăn Quỷ Đói",
    gener: ["Chính kịch", "Kịch tính", "Kinh dị"],
    year: 2023,
    time: "116 phút",
    rate: 5.5,
    actor: [
      "Chen Keat Yoke",
      "Eric Chen",
      "Sam Chong",
      "Fabian Loo",
      "Julie Chew",
    ],
    director: "Cho We Jun",
    nation: "Malaysia",
    content:
      "Mắc kẹt ở quê nhà trong thời gian phong tỏa vì đại dịch, Bonnie đến ở nhờ tại quán cà phê cũ của gia đình và phát hiện hàng loạt bất ngờ rùng rợn.",
  },
  {
    id: 122,
    image: product10,
    title: "Thiếu Niên Và Chim Diệc",
    gener: ["Chính kịch", "Hoạt hình", "Phiêu lưu", "Viễn tưởng"],
    year: 2023,
    time: "124 phút",
    rate: 8.4,
    actor: [
      "Soma Santoki",
      "Masaki Suda",
      "Ko Shibasaki",
      "Aimyon",
      "Yoshino Kimura",
      "Takuya Kimura",
      "Keiko Takeshita",
      "Jun Fubuki",
      "Sawako Agawa",
      "Karen Takizawa",
    ],
    director: "Hayao Miyazaki",
    nation: "Japan",
    content:
      "Thiếu Niên Và Chim Diệc The Boy and the Heron (2023) đến từ Studio Ghibli và đạo diễn Miyazaki Hayao, bộ phim là câu chuyện về hành trình kỳ diệu của cậu thiếu niên Mahito trong một thế giới hoàn toàn mới lạ. Trải qua nỗi đau mất mẹ cùng mối quan hệ chẳng mấy vui vẻ với gia đình cũng như bạn học, Mahito dần cô lập bản thân… cho đến khi cậu gặp một chú chim diệc biết nói kỳ lạ. Mahito cùng chim diệc bước vào một tòa tháp bí ẩn, nơi một thế giới thần kỳ mở ra, đưa cậu gặp gỡ những người mình yêu thương… trong một nhân dạng hoàn toàn khác.",
  },
  {
    id: 123,
    image: product11,
    title: "Godzilla Đại Chiến Kong",
    gener: ["Hành động", "Kịch tính", "Phiêu lưu", "Viễn tưởng"],
    year: 2021,
    time: "114 phút",
    rate: 9.1,
    actor: [
      "Alexander Skarsgård",
      "Millie Bobby Brown",
      "Rebecca Hall",
      "Brian Tyree Henry",
      "Shun Oguri",
      "Eiza González",
      "Julian Dennison",
      "Lance Reddick",
      "Kyle Chandler",
      "Demián Bichir",
    ],
    director: "Adam Wingard",
    nation: "USA",
    content:
      "Godzilla Đại Chiến Kong - Godzilla vs. Kong (2021) khi hai kẻ thù truyền kiếp gặp nhau trong một trận chiến ngoạn mục, số phận của cả thế giới vẫn còn bị bỏ ngỏ… Bị đưa khỏi Đảo Đầu Lâu, Kong cùng Jia, một cô bé mồ côi có mối liên kết mạnh mẽ với mình và đội bảo vệ đặc biệt hướng về mái nhà mới. Bất ngờ, nhóm đụng độ phải Godzilla hùng mạnh, tạo ra một làn sóng hủy diệt trên toàn cầu. Thực chất, cuộc chiến giữa hai kẻ khổng lồ dưới sự thao túng của các thế lực vô hình mới chỉ là điểm khởi đầu để khám phá những bí ẩn nằm sâu trong tâm Trái đất.",
  },
  {
    id: 124,
    image: product12,
    title: "Tình Chị Duyên Em",
    gener: ["Chiếu rạp", "Chính kịch", "Tâm lý", "Tình cảm"],
    year: 2023,
    time: "122 phút",
    rate: 9.8,
    actor: [
      "Thitiya Jirapornsilp",
      "Anthony Buisseret",
      "Supakson Chaimongkol",
      "Natee Ngamneawprom",
      "Karuna Looktumthong",
      "Kantapon Jindataweephol",
      "Pratya Patong",
    ],
    director: "Chantavit Dhanasevi",
    nation: "Thailand",
    content:
      "Tình Chị Duyên Em - You & Me & Me (2023) tình chị em tưởng chừng không thể rạn nứt cho đến khi chàng trai Mark chen vào giữa họ. Khi cặp song sinh phải đối mặt với “mối tình đầu không thể chia sẻ” như những thứ khác, cuộc xung đột nội tâm này sẽ dẫn họ bước sang giai đoạn mới của cuộc đời như thế nào?",
  },
];

export const geners = [
  "Cổ trang",
  "Bí ẩn",
  "Võ thuật",
  "Phiêu lưu",
  "Viễn tưởng",
  "Hành động",
  "Kinh dị",
  "Kịch tính",
  "Hài hước",
  "Gia đình",
  "Hoạt hình",
  "Tình cảm",
  "Học đường",
  "Lãng mạn",
  "Chính kịch",
  "Chiến tranh",
  "Khoa học",
  "Tài liệu",
  "Điện ảnh",
  "Chiếu rạp",
];

export const news = [
  {
    id: 1001,
    image: news1,
    title: "Các bộ phim hay nhất thập kỉ",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, saepe asperiores mollitia placeat fugiat porro deleniti.",
    date: "1-3-2024",
  },
  {
    id: 1002,
    image: news1,
    title: "Top 10 bộ phim nên xem trong tháng 4 này!!",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, saepe asperiores mollitia placeat fugiat porro deleniti.",
    date: "22-3-2024",
  },
  {
    id: 1003,
    image: news1,
    title: "Phim sắp ra mắt năm 2024",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, saepe asperiores mollitia placeat fugiat porro deleniti.",
    date: "15-2-2024",
  },
  {
    id: 1004,
    image: news1,
    title: "Cập nhật phim mới nhất",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, saepe asperiores mollitia placeat fugiat porro deleniti.",
    date: "10-3-2024",
  },
];

export const comment = [
  {
    id: 1100,
    name: "John",
    avatar: user,
    text:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
    date: "30.08.2018",
    likes: 18,
    dislike: 7,
  },
  {
    id: 1101,
    name: "Alex",
    avatar: user,
    text:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
    date: "30.08.2018",
    likes: 18,
    dislike: 7,
  },
  {
    id: 1102,
    name: "Cindy",
    avatar: user,
    text:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
    date: "30.08.2018",
    likes: 18,
    dislike: 7,
  },
];

export const navData = [
  {
    id: 0,
    link: "/",
    content: "Trang chủ",
  },
  {
    id: 1,
    link: "/TheLoai",
    content: "Thể loại",
  },
  {
    id: 2,
    link: "/Trailer",
    content: "Trailer",
  },
  {
    id: 3,
    link: "/YeuThich",
    content: "Yêu thích",
  },
];

export const responsive = {
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 3,
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};
